trigger:
  branches:
    include:
      - master
      - rel/*
  paths:
    include:
      - Rx.NET/Source/*
      - .editorconfig
      - .vsts.rx-ci.yml
      - .vsts.rx-shared.yml

queue: Hosted VS2017

variables: 
  BuildConfiguration: Release
  BuildPlatform: Any CPU
    
steps:
- template: .vsts.rx-shared.yml
  parameters:
    signStep:
    - task: PowerShell@2
      displayName: Authenticode Sign Packages
      inputs:
        filePath: Rx.NET/Source/build/Sign-Package.ps1
      env:
        SignClientUser: $(SignClientUser)
        SignClientSecret: $(SignClientSecret)
        ArtifactDirectory: $(Build.ArtifactStagingDirectory)\artifacts